//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoStudioApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhotoSessionRequisite
    {
        public int Id { get; set; }
        public int PhotoSessionId { get; set; }
        public int RequisiteId { get; set; }
        public int Amount { get; set; }
    
        public virtual PhotoSession PhotoSession { get; set; }
        public virtual Requisite Requisite { get; set; }
    }
}
