//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoStudioApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhotoSession
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhotoSession()
        {
            this.PhotoSessionRequisite = new HashSet<PhotoSessionRequisite>();
        }
    
        public int Id { get; set; }
        public int ClientId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime PhotoSessionDate { get; set; }
        public int PhotographId { get; set; }
        public Nullable<int> StudioId { get; set; }
        public string Address { get; set; }
        public Nullable<int> ThemeId { get; set; }
        public string Comment { get; set; }
        public System.TimeSpan PhotoSessionTime { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string Catalog { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Photograph Photograph { get; set; }
        public virtual Status Status { get; set; }
        public virtual Studio Studio { get; set; }
        public virtual Theme Theme { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhotoSessionRequisite> PhotoSessionRequisite { get; set; }
    }
}
